// Optimized course data with smaller images
export const COURSES = [
  {
    "id": 1,
    "name": "MS-Office",
    "logo": "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=300&fit=crop&crop=center&q=75",
    "description": "Master Microsoft Office Suite including Word, Excel, PowerPoint. Essential skills for any professional environment.",
    "duration": "3 months",
    "features": ["Word Processing", "Spreadsheets", "Presentations"],
    "category": "Office",
    "searchKeys": [
      "ms office",
      "microsoft office",
      "ms-office",
      "word",
      "microsoft word",
      "excel",
      "microsoft excel",
      "powerpoint",
      "ms powerpoint",
      "ppt",
      "office tools",
      "office software",
      "computer basics",
      "basic computer",
      "basic computer course",
      "ccc",
      "computer competency course",
      "data entry",
      "typing",
      "office automation",
      "office suite",
      "office training",
      "administrative skills"
    ]
  },
  {
    "id": 2,
    "name": "Tally Prime (GST) with Accounting",
    "logo": "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&h=300&fit=crop&crop=center&q=75",
    "description": "Learn complete accounting with Tally Prime including GST compliance, inventory management, and financial reporting.",
    "duration": "3 months",
    "features": ["GST Compliance", "Inventory Management", "Financial Reports", "Tax Filing"],
    "category": "Accounting",
    "searchKeys": [
      "tally prime",
      "tally",
      "tally prime gst",
      "tally gst",
      "tally accounting",
      "tally prime course",
      "accounting",
      "bookkeeping",
      "gst compliance",
      "gst return",
      "tax filing",
      "inventory management",
      "financial reporting",
      "accounts",
      "ledger",
      "voucher entry",
      "tally erp",
      "tally prime training",
      "finance",
      "small business accounting"
    ]
  },
  {
    "id": 3,
    "name": "Adobe Photoshop",
    "logo": "https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=400&h=300&fit=crop&crop=center&q=75",
    "description": "Master photo editing, digital art, and graphic design with Adobe Photoshop. Create stunning visuals and manipulate images professionally.",
    "duration": "1 Month",
    "features": ["Photo Editing", "Digital Art", "Layer Management", "Color Correction"],
    "category": "Design",
    "searchKeys": [
      "photoshop",
      "adobe photoshop",
      "photo editing",
      "image editing",
      "digital art",
      "graphic design",
      "layer management",
      "retouching",
      "photo retouch",
      "color correction",
      "masking",
      "compositing",
      "creative cloud photoshop",
      "psd",
      "photoshop training",
      "photoshop course",
      "photoshop basics",
      "photo manipulation",
      "design tools"
    ]
  },
  {
    "id": 4,
    "name": "Adobe CorelDraw",
    "logo": "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&h=300&fit=crop&crop=center&q=75",
    "description": "Learn vector graphics design with CorelDraw. Create logos, illustrations, and professional graphics for print and digital media.",
    "duration": "1 Month",
    "features": ["Vector Graphics", "Logo Design", "Illustrations", "Print Design"],
    "category": "Design",
    "searchKeys": [
      "coreldraw",
      "adobe coreldraw",
      "corel draw",
      "vector graphics",
      "logo design",
      "illustration",
      "print design",
      "vdesign",
      "cdr",
      "coreldraw course",
      "coreldraw training",
      "vector art",
      "graphic illustration",
      "advertising design",
      "package design",
      "coreldraw basics"
    ]
  },
  {
    "id": 5,
    "name": "Adobe Illustrator",
    "logo": "https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=400&h=300&fit=crop&crop=center&q=75",
    "description": "Master vector illustration and graphic design with Adobe Illustrator. Create scalable graphics, logos, and artwork.",
    "duration": "1 Month",
    "features": ["Vector Illustration", "Logo Creation", "Typography", "Brand Design"],
    "category": "Design",
    "searchKeys": [
      "illustrator",
      "adobe illustrator",
      "ai",
      "vector graphics",
      "logo creation",
      "graphic design",
      "typography",
      "brand design",
      "illustration",
      "scalable graphics",
      "svg",
      "icon design",
      "adobe ai",
      "illustrator course",
      "adobe illustrator training",
      "vector illustration"
    ]
  },
  {
    "id": 6,
    "name": "Adobe InDesign",
    "logo": "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=300&fit=crop&crop=center&q=75",
    "description": "Learn professional page layout and desktop publishing with Adobe InDesign. Design magazines, brochures, and books.",
    "duration": "1 month",
    "features": ["Page Layout", "Typography", "Print Design", "Digital Publishing"],
    "category": "Design",
    "searchKeys": [
      "indesign",
      "adobe indesign",
      "page layout",
      "desktop publishing",
      "magazine design",
      "brochure design",
      "book layout",
      "typography",
      "print design",
      "adobe indesign course",
      "indesign training",
      "layout design",
      "dps",
      "publishing software",
      "digital publishing"
    ]
  },
  {
    "id": 7,
    "name": "Advanced Excel with AI & ChatGPT",
    "logo": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=300&fit=crop&crop=center&q=75",
    "description": "Master advanced Excel functions, data analysis, and integrate AI tools like ChatGPT for enhanced productivity and automation.",
    "duration": "2 months",
    "features": ["Advanced Formulas", "Data Analysis", "AI Integration", "Automation"],
    "category": "Technology",
    "searchKeys": [
      "advanced excel",
      "excel advanced",
      "excel with ai",
      "chatgpt excel",
      "excel chatgpt",
      "vlookup",
      "hlookup",
      "pivot table",
      "pivot tables",
      "power query",
      "power pivot",
      "macros",
      "vba",
      "excel macros",
      "data analysis",
      "spreadsheet automation",
      "excel formulas",
      "power bi integration",
      "data cleaning",
      "data transformation",
      "excel training",
      "xlsx"
    ]
  },
  {
    "id": 8,
    "name": "English Typing",
    "logo": "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=300&fit=crop&crop=center&q=75",
    "description": "Improve your typing speed and accuracy in both Hindi and English. Essential skill for data entry and office work.",
    "duration": "4 months",
    "features": ["Speed Building", "Accuracy Training", "Bilingual Typing", "Practice Tests"],
    "category": "Office",
    "searchKeys": [
      "typing",
      "english typing",
      "hindi typing",
      "touch typing",
      "typing speed",
      "typing course",
      "keyboard training",
      "data entry",
      "typing practice",
      "typing test",
      "10 finger typing",
      "typing accuracy",
      "office typing",
      "typing for beginners",
      "typing improvement",
      "typewriting",
      "typewriting course"
    ]
  },
  {
    "id": 9,
    "name": "AutoCAD 2D & 3D",
    "logo": "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=100&h=100&fit=crop&crop=center",
    "description": "Learn computer-aided design with AutoCAD. Create precise 2D drawings and 3D models for engineering and architecture.",
    "duration": "2 months",
    "features": ["2D Drafting", "3D Modeling", "Technical Drawing", "Engineering Design"],
    "category": "Engineering",
    "searchKeys": [
      "autocad",
      "autocad 2d",
      "autocad 3d",
      "cad",
      "2d drafting",
      "3d modeling",
      "technical drawing",
      "engineering design",
      "autocad course",
      "autocad training",
      "dwg",
      "cad design",
      "architectural cad",
      "mechanical cad",
      "civil cad",
      "autocad basics",
      "autocad advanced"
    ]
  },
  {
    "id": 10,
    "name": "C & C++ Programming",
    "logo": "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=100&h=100&fit=crop&crop=center",
    "description": "Master the fundamentals of programming with C and C++. Build strong foundation for software development and system programming.",
    "duration": "4 months",
    "features": ["Programming Basics", "Data Structures", "Object-Oriented Programming", "System Programming"],
    "category": "Programming",
    "searchKeys": [
      "c programming",
      "c++",
      "c and c++",
      "c plus plus",
      "cplusplus",
      "cpp",
      "system programming",
      "data structures c",
      "ooph c++",
      "pointer programming",
      "memory management",
      "algorithms c",
      "programming basics",
      "software development",
      "c course",
      "c++ course",
      "competitive programming",
      "embedded c",
      "desktop applications",
      "gcc",
      "g++"
    ]
  },
  {
    "id": 11,
    "name": "Java Programming",
    "logo": "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=100&h=100&fit=crop&crop=center",
    "description": "Learn Java programming from basics to advanced concepts. Build enterprise applications and understand object-oriented programming.",
    "duration": "2 months",
    "features": ["OOP Concepts", "Enterprise Development", "Spring Framework", "Database Integration"],
    "category": "Programming",
    "searchKeys": [
      "java",
      "java programming",
      "jdk",
      "jre",
      "java course",
      "core java",
      "advanced java",
      "spring",
      "spring boot",
      "object oriented programming",
      "oop java",
      "java backend",
      "enterprise java",
      "servlets",
      "jsp",
      "hibernate",
      "maven",
      "gradle",
      "java training",
      "j2ee",
      "java developer"
    ]
  },
  {
    "id": 12,
    "name": "Python Programming",
    "logo": "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=100&h=100&fit=crop&crop=center",
    "description": "Master Python programming for web development, data analysis, and automation. One of the most versatile programming languages.",
    "duration": "2 months",
    "features": ["Data Analysis", "Automation", "Machine Learning Basics"],
    "category": "Programming",
    "searchKeys": [
      "python",
      "python programming",
      "py",
      "python course",
      "python training",
      "django",
      "flask",
      "data analysis python",
      "automation python",
      "machine learning basics",
      "pandas",
      "numpy",
      "web development python",
      "scripting",
      "python for beginners",
      "python intermediate",
      "python projects",
      "ai python"
    ]
  },
  {
    "id": 13,
    "name": "Advanced Internet",
    "logo": "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=100&h=100&fit=crop&crop=center",
    "description": "Master advanced internet technologies, web services, cloud computing, and digital communication tools for modern business.",
    "duration": "1 month",
    "features": ["Web Technologies", "Cloud Services", "Digital Communication", "Online Security"],
    "category": "Technology",
    "searchKeys": [
      "advanced internet",
      "internet technologies",
      "web services",
      "cloud computing",
      "digital communication",
      "online security",
      "networking basics",
      "internet course",
      "web protocols",
      "http",
      "https",
      "rest api",
      "api integration",
      "cloud services basics",
      "digital tools",
      "web tools",
      "internet training"
    ]
  },
  {
    "id": 14,
    "name": "Video Editing",
    "logo": "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=100&h=100&fit=crop&crop=center",
    "description": "Learn professional video editing techniques using industry-standard software. Create engaging content for social media and marketing.",
    "duration": "1 month",
    "features": ["Video Editing", "Color Grading", "Audio Editing", "Motion Graphics"],
    "category": "Media",
    "searchKeys": [
      "video editing",
      "video editor",
      "premiere pro",
      "final cut",
      "davinci resolve",
      "color grading",
      "motion graphics",
      "editing course",
      "video production",
      "youtube editing",
      "social media videos",
      "post production",
      "audio editing",
      "video transitions",
      "vfx basics",
      "film editing"
    ]
  },
  {
    "id": 15,
    "name": "Data Analytics",
    "logo": "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=100&h=100&fit=crop&crop=center",
    "description": "Learn data analysis, visualization, and business intelligence. Work with real datasets and make data-driven decisions.",
    "duration": "6 months",
    "features": ["Data Analysis", "Visualization", "Statistical Analysis", "Business Intelligence"],
    "category": "Analytics",
    "searchKeys": [
      "data analytics",
      "data analysis",
      "business intelligence",
      "data visualization",
      "power bi",
      "tableau",
      "excel analytics",
      "sql for analytics",
      "statistics",
      "data cleaning",
      "dashboards",
      "data scientist basics",
      "analytics course",
      "big data basics",
      "data driven decisions",
      "python analytics",
      "r analytics"
    ]
  },
  {
    "id": 18,
    "name": "Revit",
    "logo": "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=100&h=100&fit=crop&crop=center",
    "description": "Learn Building Information Modeling (BIM) with Autodesk Revit. Design and document building projects with precision.",
    "duration": "2 months",
    "features": ["BIM Modeling", "Architectural Design", "MEP Systems", "Project Documentation"],
    "category": "Architecture",
    "searchKeys": [
      "revit",
      "autodesk revit",
      "bim",
      "building information modeling",
      "architectural design",
      "mep revit",
      "revit course",
      "revit training",
      "revit architecture",
      "construction modeling",
      "revit families",
      "project documentation",
      "architectural bim",
      "revit basics",
      "revit advanced"
    ]
  },
  {
    "id": 19,
    "name": "NX-CAD",
    "logo": "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=100&h=100&fit=crop&crop=center",
    "description": "Master advanced CAD design with Siemens NX. Professional 3D modeling and simulation for engineering applications.",
    "duration": "2 months",
    "features": ["3D Modeling", "Simulation", "Engineering Design", "Manufacturing"],
    "category": "Engineering",
    "searchKeys": [
      "nx cad",
      "siemens nx",
      "nx-cad",
      "3d modeling",
      "cad simulation",
      "engineering design",
      "manufacturing cad",
      "nx course",
      "siemens nx training",
      "cad software",
      "product design",
      "complex modeling",
      "assembly modeling",
      "tooling design"
    ]
  },
  {
    "id": 20,
    "name": "Stenography Course",
    "logo": "https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=100&h=100&fit=crop&crop=center",
    "description": "Learn shorthand writing and stenography for court reporting, secretarial work, and fast note-taking in professional settings.",
    "duration": "3 months",
    "features": ["Shorthand Writing", "Speed Building", "Court Reporting", "Professional Documentation"],
    "category": "Office",
    "searchKeys": [
      "stenography",
      "stenography course",
      "shorthand",
      "court reporting",
      "steno",
      "shorthand writing",
      "secretarial course",
      "note taking",
      "speed writing",
      "steno training",
      "steno shorthand",
      "transcription",
      "professional documentation",
      "typing stenography"
    ]
  },
  {
    "id": 21,
    "name": "Spoken English",
    "logo": "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=100&h=100&fit=crop&crop=center",
    "description": "Improve your English speaking skills, pronunciation, and confidence. Essential for career growth and communication.",
    "duration": "3 months",
    "features": ["Speaking Practice", "Pronunciation", "Grammar", "Confidence Building"],
    "category": "Language",
    "searchKeys": [
      "spoken english",
      "english speaking",
      "english conversation",
      "pronunciation",
      "communication skills",
      "fluency",
      "spoken english course",
      "english practice",
      "conversation practice",
      "job interview english",
      "business english",
      "esl",
      "accent training",
      "confidence building",
      "oral english"
    ]
  },
  {
    "id": 22,
    "name": "Computer Hardware",
    "logo": "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=100&h=100&fit=crop&crop=center",
    "description": "Learn computer hardware assembly, troubleshooting, and maintenance. Understand components and repair techniques.",
    "duration": "3 months",
    "features": ["Hardware Assembly", "Troubleshooting", "Component Knowledge", "Repair Techniques"],
    "category": "Hardware",
    "searchKeys": [
      "computer hardware",
      "hardware course",
      "pc assembly",
      "troubleshooting",
      "hardware repair",
      "component knowledge",
      "motherboard",
      "cpu",
      "ram",
      "hard disk",
      "ssd",
      "pc maintenance",
      "it hardware",
      "desktop repair",
      "laptop repair",
      "hardware technician",
      "hardware training"
    ]
  }
];